spring:
  application:
    name: cloud-provide-8401
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8401