spring:
  application:
    name: cloud-nacos-payment-9001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: '*'