spring:
  application:
    name: spring-cloud-config3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:WilsonWeng-hub/springcloud-config.git
          search-paths:
            - springcloud-config
          label: master
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

server:
  port: 3344
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"