server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3308/springcloudtest?useUnicode=true&charcterEncodeing=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002  #服务名称
    prefer-ip-address: true #显示ip地址
    #Eureka服务端在收到最后于一次心跳后等待时间上限，默认90s，超时将剔除服务
    lease-expiration-duration-in-seconds: 90
    #Eureka客户端向服务端发送心跳的时间间隔，默认30s
    lease-renewal-interval-in-seconds: 20

mybatis:
  type-aliases-package: com.wilson.springcloud.enties
  mapper-locations: classpath:mapper/*.xml

