spring:
  application:
    name: cloud-gateway-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 9527